# Generated by Django 3.0.8 on 2020-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='Landscape', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
